### ISSUE TITLE
Audio Clip cuts off.

### ISSUE THREAD

**Issue by LacyDoes** [Not-Enough-Photons/Hitmarkers#1]
The "finisher" clips are cut off by the hitmaker object deleting itself before the clip can finish playing.
I'm unsure how the hit markers are structured but from what I assume is the clips are parented under the hit marker game object.

I noticed this when it plays in normal speed. At slow speed, the object takes longer to delete therefore the clip does not remove itself.

Methods that could resolve:
_Mind you, I've never personally worked on modding for Bone works or even know how the game is structured so I'm unsure if these would work._

- Keeping the position of the clip relative to the hit marker but playing under root space. (Floods root but avoids clipping)
- Increase the cleanup delay (This would not account for clips being practically infinite possible lengths.)
- Detect audio clip length and compensate for the delay by clip length. (more calculating than necessary really)

**Comment by adamd3v** [comment]
The cut-off is due to the audio source being on the hitmarker object itself. I'll switch to pooled audio sometime.
