### ISSUE TITLE
[Feature Request] Small configurable additions

### ISSUE THREAD

**Issue by LacyDoes** [Not-Enough-Photons/Hitmarkers#2]
Some additions to the menu to allow more user end configuring.

1. Hit marker playback/animation speed (Recommend to clamp a MIN time for this to avoid frozen hitmakers)
2. Finisher playback/animation speed
3. Configurable Colors for Cross and Skull (This really isn't necessary but would be fun)
4. Audio clip volume (Sorta just QoL)
5. Replaceable Sprites either file scan/inject for user-created sprite or Presets to choose from. (Don't know how you'd go about doing this but if you can- Cool!)

If I think of any more I'll edit the issue!

**Comment by adamd3v** [comment]
Sounds nice, I'll look into it!
Life Force will reward you.

**Comment by LacyDoes** [comment]
> Sounds nice, I'll look into it! Life Force will reward you.

Unsure of what you mean by reward me but good to know these will be looked into! ^^;
Love the mod by the by, makes the arena very satisfying!
