### ISSUE TITLE
Audio very low

### ISSUE THREAD

**Issue by dravpin** [Not-Enough-Photons/Hitmarkers#7]
ive raised the sfx in the bonemenu but still can barely hear the sfx because the game sfx are louder like gun shots

**Comment by Eniti-Codes** [comment]
I have the opposite problem. Not completely, but Whenever I go and adjust anything with the mod, everything goes muted. When I go in the bonemenu I was only able to fix the audio by reinstalling and not touching any settings in the bonemenu. I guess that part is glitched.
