### ISSUE TITLE
not working with patch 3

### ISSUE THREAD

**Issue by BaylieBuffel** [Not-Enough-Photons/Hitmarkers#8]
it does not work on patch 3

**Comment by adamd3v** [comment]
i think you installed it incorrectly

**Comment by BaylieBuffel** [comment]
I installed it exactly what the same way on patch 2 and then it worked but it does not work for me on patch 3

**Comment by MoonCakeToo** [comment]
skill issue?

**Comment by BaylieBuffel** [comment]
No it is working now
